AppBundle\Entity\Trade:
    type: entity
    table: trades
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        user_id:
            type: integer
        stock_option_id:
            type: integer
        quantity:
            type: integer
    manyToOne:
        user:
            targetEntity: User
            inversedBy: trades
            joinColumn:
                name: user_id
                referencedColumnName: id
        stock_option:
            targetEntity: StockOption
            inversedBy: trades
            joinColumn:
                name: stock_option_id
                referencedColumnName: id